
##Name:Roshan yadav

## Roll No. :52

## Class : SYIT

## Date of Assignment : 05/08/2026

## Date/Time of Submission :05/08/2026

# **Practical 4 Numpy**

In [1]:
import numpy as np


**a. Write a python code to create Numpy Array.**

In [4]:
a = np.array([1,2,3])
print(a)

[1 2 3]


**b. Write a python code to demonstrate basic operations on single array.**

In [7]:
print(a + 2)
print(a * 2)

[3 4 5]
[2 4 6]


**c. Write a python code to create array with 10 elements and slice element
from 1st to 5th element.**

In [9]:
b = np.array([1,2,3,4,5,6,7,8,9,10])
print(b[0:5])

[1 2 3 4 5]


**d. Write a python code to sort an array alphabetically.**

In [12]:
name = np.array(["roshan","kaushal","sunny","nitesh"])
print(np.sort(name))

['kaushal' 'nitesh' 'roshan' 'sunny']


**e. Write a python code to create a filter array that will return maximum values from an array.**

In [14]:
price = np.array([2000,300,6000,9000,9456,3256])
print(price[price > 5000])

[6000 9000 9456]
